version: 2.1

orbs:
  node: circleci/node@4.9.0

jobs:
  hiuihhihi_build_and_test:
    docker:
      - image: cimg/node:17.7
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test

workflows:
  main_workflow:
    jobs:
      - hiuihhihi_build_and_test
