module.exports.listObject = {
  id: 12345,
  id_str: '12345',
  name: 'LIST_NAME',
  uri: '/SCREEN_NAME/lists/12345',
  subscriber_count: 0,
  member_count: 259,
  mode: 'private',
  description: '実質タイムライン (2022/02/24) id_number: 12345',
  slug: '12345',
  full_name: '@SCREEN_NAME/12345',
  created_at: 'Thu Feb 24 00:36:47 +0000 2022',
  following: true,
  user: {
    id: 54321,
    id_str: '54321',
    name: 'なまえ',
    screen_name: 'SCREEN_NAME',
    location: '東京都千代田区',
    description: 'よろしくおねがいします。',
    url: 'https://t.co/HOGEHOGE',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 898,
    friends_count: 369,
    listed_count: 47,
    created_at: 'Tue Apr 24 00:49:27 +0000 2007',
    favourites_count: 57959,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: false,
    statuses_count: 110728,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '022330',
    profile_background_image_url:
      'http://abs.twimg.com/images/themes/theme15/bg.png',
    profile_background_image_url_https:
      'https://abs.twimg.com/images/themes/theme15/bg.png',
    profile_background_tile: true,
    profile_image_url:
      'http://pbs.twimg.com/profile_images/54321/jarbu13L_normal.jpg',
    profile_image_url_https:
      'https://pbs.twimg.com/profile_images/54321/jarbu13L_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/11111/22222',
    profile_link_color: 'F58EA8',
    profile_sidebar_border_color: 'A8C7F7',
    profile_sidebar_fill_color: 'C0DFEC',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: true,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false,
    translator_type: 'none',
    withheld_in_countries: [],
  },
}
