module.exports.tweetObjectV1 = {
  created_at: 'Fri Mar 25 01:00:15 +0000 2022',
  id: 1507160400655122400,
  id_str: '1507160400655122471',
  full_text: '春なにょだ🌸\n\n#にゃらん #じゃらん https://t.co/tw18Fa3FbI',
  truncated: false,
  display_text_range: [0, 19],
  entities: {
    hashtags: [[Object], [Object]],
    symbols: [],
    user_mentions: [],
    urls: [],
    media: [[Object]],
  },
  extended_entities: { media: [[Object]] },
  source:
    '<a href="https://social.userlocal.jp/" rel="nofollow">Social Insight Post</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 158219828,
    id_str: '158219828',
    name: 'にゃらん',
    screen_name: 'nyalan_jalan',
    location: '川崎あたり',
    description:
      '私はにゃらん。 ふらっと気の向くままに旅に出るにょが大好きにゃ。 温泉に自然、美味しいごはんと、旅は楽しみがいっぱいなにょだ♪ 旅先から自由きままにツイートするにょだ。 ムムム、次はどこに行こうかにゃ。',
    url: null,
    entities: { description: [Object] },
    protected: false,
    followers_count: 164054,
    friends_count: 2,
    listed_count: 2978,
    created_at: 'Tue Jun 22 02:59:49 +0000 2010',
    favourites_count: 8093,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: true,
    statuses_count: 3290,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: true,
    profile_background_color: 'FFFFFF',
    profile_background_image_url:
      'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https:
      'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url:
      'http://pbs.twimg.com/profile_images/1112822880658546688/TPkonOXN_normal.jpg',
    profile_image_url_https:
      'https://pbs.twimg.com/profile_images/1112822880658546688/TPkonOXN_normal.jpg',
    profile_banner_url:
      'https://pbs.twimg.com/profile_banners/158219828/1612138067',
    profile_link_color: '0084B4',
    profile_sidebar_border_color: 'FFFFFF',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: false,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false,
    translator_type: 'none',
    withheld_in_countries: [],
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 461,
  favorite_count: 2310,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  possibly_sensitive_appealable: false,
  lang: 'ja',
}
