name: (GitHub Actions) Node.js CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

env:
  TZ: Asia/Tokyo

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - name: Node.js のセットアップ
      uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
        cache: 'yarn'
        cache-dependency-path: yarn.lock
    - name: $ yarn install を実行する
      run: |
        yarn install --frozen-lockfile
    - name: Jest を実行する
      run: |
        yarn test
    - name: Codecov の結果をアップロードする
      uses: codecov/codecov-action@v3
      with:
        directory: ./.coverage
